version: "2"
services:
 sat-spot-serv:
  build: ./web/
  ports:
   - 80:3000
  command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; node db/index.js createTables; node app.js'
  depends_on:
   - db
 db:
  image: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_PASSWORD=password
   - POSTGRES_USER=postgres
   - POSTGRES_DB=satellite-db
